# Generated by Django 3.1.3 on 2020-11-06 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_date', models.DateField(auto_now=True)),
                ('task_start_time', models.TimeField(auto_now=True)),
                ('task_end_time', models.TimeField()),
                ('details', models.CharField(max_length=254)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('E', 'Expected'), ('F', 'Finished')], default='P', max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
